import 'dart:convert';
import 'dart:io';
import 'package:flutter/foundation.dart';
import 'package:http/http.dart' as http;

import '../../env/env.dart';
import '../../models/user_profile.dart';
import '../../services/firebase_service.dart';
import '../../services/local_cache_service.dart';

/// Converts AI-generated HTML to a PDF File using a remote Playwright microservice.
class HtmlToPdfPipeline {
  HtmlToPdfPipeline._();
  static final HtmlToPdfPipeline instance = HtmlToPdfPipeline._();

  // PDF Engine URL injected via envied.
  static final _pdfEngineUrl = Env.pdfEngineUrl;

  final _cache = LocalCacheService.instance;

  Future<File> convert({
    required String html,
    required String uid,
    required String pid,
    required String docId,
  }) async {
    debugPrint('[Pipeline] Converting HTML → PDF via Remote Engine for doc: $docId');

    if (html.trim().isEmpty) throw Exception('Empty HTML content');

    // 1. Check Cache
    final cached = await _cache.getCachedPdf(uid, pid, docId);
    if (cached != null) {
      debugPrint('[Pipeline] PDF cache hit');
      return cached;
    }

    // 2. Fetch Profile for Tier Checks (Watermarking)
    final profile = await FirebaseService.instance.fetchProfile();
    final limits = TierLimits.get(profile.tier);

    // 3. Prepare HTML
    final processedHtml = _prepareHtml(html, watermark: limits.watermarked);

    try {
      // 4. Request PDF from Microservice
      final response = await http.post(
        Uri.parse(_pdfEngineUrl),
        headers: {'Content-Type': 'application/json'},
        body: jsonEncode({'html': processedHtml}),
      );

      if (response.statusCode != 200) {
        throw Exception(
          'Failed to generate PDF. Engine returned ${response.statusCode}: ${response.body}',
        );
      }

      final bytes = response.bodyBytes;

      // 5. Cache and Return
      final file = await _cache.cachePdfBytes(bytes, uid, pid, docId);
      await _cache.cacheHtml(html, uid, pid, docId);

      debugPrint('[Pipeline] PDF saved — ${bytes.length} bytes');
      return file;
    } catch (e) {
      debugPrint('[Pipeline] Engine error: $e');
      rethrow;
    }
  }

  /// Deletes the cached PDF so the next export re-renders fresh content.
  Future<void> invalidate(String uid, String pid, String docId) async {
    final path = await _cache.pdfPath(uid, pid, docId);
    final file = File(path);
    if (file.existsSync()) {
      await file.delete();
      debugPrint('[Pipeline] PDF cache invalidated: $docId');
    }
  }

  /// Injects print-safe CSS and optional watermark.
  String _prepareHtml(String html, {bool watermark = false}) {
    // Remove HTML comments
    final commentRegex = RegExp(r'<!--[\s\S]*?-->');
    String cleanedHtml = html.replaceAll(commentRegex, '');

    String watermarkInjection = '';
    if (watermark) {
      watermarkInjection = '''
<div id="bizdocx-watermark" style="
  position: fixed;
  bottom: 20px;
  right: 20px;
  opacity: 0.4;
  font-family: sans-serif;
  font-size: 12px;
  color: #888;
  z-index: 9999;
  pointer-events: none;
">
  Generated by <b>BizDocx</b> - Upgrade your plan to remove watermark
</div>
<style>
  /* Diagonal watermark for free tier */
  body::before {
    content: "BIZDOCX FREE TIER";
    position: fixed;
    top: 50%;
    left: 50%;
    transform: translate(-50%, -50%) rotate(-45deg);
    font-size: 80px;
    color: rgba(0, 0, 0, 0.03);
    pointer-events: none;
    z-index: 0;
    white-space: nowrap;
  }
</style>
''';
    }

    const baseStyles = '''
<style>
  @media print {
    * {
      -webkit-print-color-adjust: exact !important;
      print-color-adjust: exact !important;
    }
  }
  body {
    margin: 0 !important;
    padding: 0 !important;
  }
</style>
''';

    final injection = '$baseStyles$watermarkInjection';

    if (cleanedHtml.contains('</head>')) {
      cleanedHtml = cleanedHtml.replaceFirst('</head>', '$injection</head>');
    } else if (cleanedHtml.contains('<body')) {
      cleanedHtml = cleanedHtml.replaceFirst('<body', '<head>$injection</head><body');
    } else {
      cleanedHtml = '<html><head>$injection</head><body>$cleanedHtml</body></html>';
    }

    if (watermark && cleanedHtml.contains('</body>')) {
      cleanedHtml = cleanedHtml.replaceFirst('</body>', '$watermarkInjection</body>');
    } else if (watermark) {
      cleanedHtml += watermarkInjection;
    }

    return cleanedHtml;
  }
}
