// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBqx4wsnEJD9MvWs-wua8D2bZZSeXXBrRI',
    appId: '1:776742749745:web:ef6707a2a1ef1cb3613710',
    messagingSenderId: '776742749745',
    projectId: 'bizdocx-app',
    authDomain: 'bizdocx-app.firebaseapp.com',
    storageBucket: 'bizdocx-app.firebasestorage.app',
    measurementId: 'G-3SM3L74FV8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBA9oAn0WfxnS-9JBxugQnemzQ9vkA2h4A',
    appId: '1:776742749745:android:59c2e48401f35859613710',
    messagingSenderId: '776742749745',
    projectId: 'bizdocx-app',
    storageBucket: 'bizdocx-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDohcUmwMM2HqhDChJgygfvnrtD78djizA',
    appId: '1:776742749745:ios:fca3038204701e65613710',
    messagingSenderId: '776742749745',
    projectId: 'bizdocx-app',
    storageBucket: 'bizdocx-app.firebasestorage.app',
    iosBundleId: 'com.empyrealworks.bizdocx',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDohcUmwMM2HqhDChJgygfvnrtD78djizA',
    appId: '1:776742749745:ios:fca3038204701e65613710',
    messagingSenderId: '776742749745',
    projectId: 'bizdocx-app',
    storageBucket: 'bizdocx-app.firebasestorage.app',
    iosBundleId: 'com.empyrealworks.bizdocx',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBqx4wsnEJD9MvWs-wua8D2bZZSeXXBrRI',
    appId: '1:776742749745:web:b092e2531a725e97613710',
    messagingSenderId: '776742749745',
    projectId: 'bizdocx-app',
    authDomain: 'bizdocx-app.firebaseapp.com',
    storageBucket: 'bizdocx-app.firebasestorage.app',
    measurementId: 'G-N0JD5BD57H',
  );
}
